import { defineConfig } from "tsdown";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/assistant.ts",
    "src/adapter.ts",
    "src/features.ts",
    "src/filters.ts",
    "src/header-filters.ts",
    "src/editing.ts",
    "src/batch-editing.ts",
    "src/density.ts",
    "src/fullscreen.ts",
    "src/saved-views.ts",
    "src/cell-navigation.ts",
    "src/find-in-table.ts",
    "src/status-bar.ts",
    "src/column-menu.ts",
    "src/column-selection.ts",
    "src/selection-stats.ts",
    "src/bulk-actions.ts",
    "src/command-palette.ts",
    "src/context-menu.ts",
    "src/side-panel.ts",
    "src/print.ts",
    "src/export-csv.ts",
    "src/export-pdf.ts",
    "src/export-xlsx.ts",
    "src/formula.ts",
    "src/pivot.ts",
    "src/stream.ts",
    "src/sparkline.ts",
  ],
  platform: "neutral",
  format: ["esm", "cjs"],
  tsconfig: "./tsconfig.build.json",
  dts: { vue: true },
  sourcemap: true,
  clean: true,
  treeshake: true,
  deps: { neverBundle: ["vue", "@adapttable/core"] },
  outExtensions: ({ format }) => ({
    js: format === "es" ? ".js" : ".cjs",
    dts: format === "es" ? ".d.ts" : ".d.cts",
  }),
});
