/** Compile upstream Bootstrap, then bound every rule to this kit's host. */
import { readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

import postcss from "postcss";
import { format } from "prettier";
import * as sass from "sass";

const require = createRequire(import.meta.url);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const bootstrap = path.dirname(require.resolve("bootstrap/package.json"));
const parts = [
  "root",
  "reboot",
  "tables",
  "forms",
  "buttons",
  "transitions",
  "dropdown",
  "card",
  "pagination",
  "badge",
  "alert",
  "progress",
  "close",
  "modal",
  "tooltip",
  "popover",
  "spinners",
  "offcanvas",
  "helpers",
];
const source = [
  "functions",
  "variables",
  "variables-dark",
  "maps",
  "mixins",
  ...parts,
]
  .map((part) => `@import "${part}";`)
  .join("\n");
const compiled = sass.compileString(source, {
  loadPaths: [path.join(bootstrap, "scss")],
  style: "expanded",
  silenceDeprecations: [
    "import",
    "global-builtin",
    "color-functions",
    "if-function",
  ],
}).css;
const css = postcss.parse(compiled);
const scope = ".adapttable-ngx-bootstrap";
css.walkRules((rule) => {
  if (rule.parent?.type === "atrule" && /keyframes$/u.test(rule.parent.name))
    return;
  rule.selectors = [
    ...new Set(
      rule.selectors.flatMap((selector) => {
        if (selector === ":root" || selector === "body") return scope;
        if (selector === "[data-bs-theme=light]")
          return `${scope}[data-bs-theme="light"]`;
        if (selector === "[data-bs-theme=dark]")
          return `${scope}[data-bs-theme="dark"]`;
        if (selector.startsWith("[data-bs-theme=dark] "))
          return [
            `${scope}[data-bs-theme="dark"] ${selector.slice("[data-bs-theme=dark] ".length)}`,
            `${scope} ${selector}`,
          ];
        return `${scope} ${selector}`;
      })
    ),
  ];
});
// Animations are document-global names even when their element rules are scoped.
css.walkAtRules(/keyframes$/u, (rule) => {
  rule.params = `adapttable-ngx-bootstrap-${rule.params}`;
});
css.walkDecls(/animation/u, (decl) => {
  decl.value = decl.value.replace(
    /\b(spinner-border|spinner-grow|progress-bar-stripes)\b/gu,
    "adapttable-ngx-bootstrap-$1"
  );
});
const additions = await readFile(path.join(root, "src/styles.css"), "utf8");
await writeFile(
  path.join(root, "styles.css"),
  await format(
    `/*! Bootstrap v5.3.8 | Copyright 2011-2025 The Bootstrap Authors | MIT: see BOOTSTRAP-LICENSE. Generated by scripts/build-styles.mjs. */\n${css.toString()}\n${additions}`,
    { parser: "css" }
  )
);
await writeFile(
  path.join(root, "BOOTSTRAP-LICENSE"),
  await readFile(path.join(bootstrap, "LICENSE"))
);
