export const workspaceCopy = {
  en: {
    manageViews: "Manage saved views",
    savedViewsHelp:
      "Save filters, sorting, grouping and density from the table’s Saved views menu. Views stay in this browser when storage is available; applying one keeps your current order edits. A default opens on a fresh link; explicit table settings in a link take priority.",
    clearRange: "Clear cell selection",
    rangeHelp:
      "Select cells in the desktop grid with Shift + arrow keys, then export. No file will be created without a current range.",
    rangeMobile:
      "Cell-range export is unavailable in cards. Choose a page or all filtered orders, or return to the desktop grid and make a new selection.",
    recoverySaved:
      "Your local orders, selection and dispatch plan will be restored after retry. Table and pivot settings remain in the URL.",
    recoveryBlocked:
      "Recovery could not save your work in this browser. Nothing was reloaded. Return to another view to keep working.",
    queueHelp:
      "Open a pending order to reveal it, select it and inspect its line items. This works across the entire workspace, including orders hidden by the current filters.",
    queueEmpty: "No orders are awaiting review.",
    reviewing: "Reviewing",
    openDetails: "Open line items",
    van: "Van",
    deliveryRun: "delivery run",
    ordersHint:
      "Start with the Review queue or search by customer. Review the line items, then mark selected orders ready to add them to Dispatch.",
    dispatchHint:
      "Only Ready orders enter this plan. Review orders stay at the desk and Dispatched orders are complete. Moves and owner changes follow the shared workspace.",
    revenueHint:
      "Edit a cost to see gross profit recalculate. Change the pivot rows or measure to compare the same authored orders from another angle.",
    ordersKeys:
      "Tab reaches controls. On desktop, arrow keys move through the grid and Shift + arrow selects cells. Cards use row controls. Escape closes overlays.",
    dispatchKeys:
      "On desktop, focus a move handle: Space lifts, arrows move, Space places and Escape cancels. On cards, use Move up and Move down. Tab reaches every control.",
    revenueKeys:
      "On desktop, arrows move through cells and F2 edits a cost. Tab reaches the pivot choices. Cards expose the same editable field and native selectors.",
    discovery: "Features in this view",
    implementation: "How this view is built",
    featureFinder: "Find a native feature",
    featureExamples: "Focused native examples",
    compare: "Compare a working kit",
    compareNote:
      "Comparisons open in a new tab so your workspace stays in place.",
    source: "Adapter source",
    sourceExample: "Source example",
    viewReference: "Feature reference",
    featureFilters: "Filters and editing",
    featureNested: "Nested tables",
    featureActions: "Actions and export",
    featureAssistant: "Assistant approvals",
    featureViews: "Saved views",
    featureTree: "Tree rows",
    featureMoves: "Row moves",
    featureSpans: "Merged cells",
    featureNavigation: "Navigation and Find",
    featureGrouping: "Grouping",
    featureFormulas: "Formulas and pivot",
    featureColumns: "Columns",
    featureFooters: "Summaries and footers",
    featureSelection: "Selection",
    featureComposition: "Combined lifecycles",
    featureUnion: "Windowed feature combination",
    invalidCost: "Enter a cost of zero or more.",
    costSaved: "Cost updated for",
    orderImplementation:
      "The native adapter owns controls. Host callbacks own edits and bulk writes. A second real DataTable renders each order’s line items; range export is available only with a current desktop selection.",
    dispatchImplementation:
      "Ready order IDs are assigned to regional runs by the host. The native tree and move controls request changes to that plan. The manifest uses native row spans while cards repeat complete delivery fields.",
    revenueImplementation:
      "The formula column supplies its computed value. Native editing updates the host’s cost, and native pivot URL state records dimension and measure changes independently of the order table.",
    brand: "AdaptTable",
    eyebrow: "Vue Unstyled / interactive workspace",
    title: "A calmer way to work with data.",
    lead: "Review orders, plan a dispatch, and understand revenue. Real tables, connected interactions, and a little room to breathe.",
    notice: "Fictional data, local changes. Vue packages are experimental.",
    orders: "Order desk",
    dispatch: "Dispatch plan",
    revenue: "Revenue review",
    nav: "Workspace views",
    language: "Language",
    layout: "Layout",
    auto: "Responsive",
    cards: "Cards",
    theme: "Dark appearance",
    guidance: "Make yourself at home",
    hint: "Search by customer. Select a few orders. Open a detail row, or ask the assistant to prepare a review.",
    keyboard: "Keyboard guide",
    keyHint:
      "Tab reaches each control. Arrow keys move through the desktop grid. Shift + arrow selects a range. Escape closes an overlay.",
    docs: "Vue guide",
    examples: "All native examples",
    help: "About this workspace",
    about:
      "Built with the real Vue Unstyled adapter. Controls are native HTML, styled here by the host. Your changes stay in this browser session.",
    ready: "Workspace ready",
    footer: "Designed for the way work actually happens.",
    total: "Orders in this workspace",
    needsReview: "Awaiting review",
    value: "Order value",
    selected: "selected",
    ordersTitle: "Keep the details in view.",
    ordersLead:
      "Find the next order to review, edit its owner, and inspect the line items without leaving your place.",
    group: "Group by region",
    groupingOff: "Ungrouped",
    groupingOn: "By region",
    exportScope: "Export",
    page: "Current page",
    loadedCards: "Loaded cards",
    range: "Selected cells",
    all: "All filtered orders",
    refresh: "Restore sample data",
    refreshed: "The original sample orders and dispatch plan are restored.",
    pause: "Pause workspace",
    resume: "Resume workspace",
    paused: "Workspace paused",
    pausedBody: "Your view is kept. Resume when you’re ready to continue.",
    local: "Changes are local to this demonstration.",
    rowDetails: "Line items",
    customer: "Customer",
    order: "Order",
    owner: "Owner",
    status: "Status",
    due: "Dispatch by",
    amount: "Value",
    region: "Region",
    pageTotal: "Page total",
    reviewNote:
      "Totals cover the current page, or the loaded cards on mobile. Exports use the scope you choose above.",
    product: "Product",
    quantity: "Quantity",
    unitPrice: "Unit price",
    subtotal: "Subtotal",
    noOrders: "No orders match this view",
    noOrdersHint: "Try a different customer name or clear the active filters.",
    clear: "Clear filters",
    loading: "Loading this workspace…",
    failure: "This workspace could not load",
    retry: "Try again",
    saved: "Owner updated for",
    invalidOwner: "Enter at least two characters for the owner.",
    bulk: "Mark ready",
    bulkTitle: "Mark selected orders ready?",
    bulkMessage:
      "Selected orders awaiting review will move to Ready and enter the dispatch plan. Completed orders stay completed.",
    bulkDone: "orders marked ready.",
    command: "Show orders awaiting review",
    commandDone: "orders awaiting review are shown and selected.",
    context: "Select this order",
    contextDone: "Selected",
    panel: "Review queue",
    panelText:
      "The owner field can be edited in place. Expand an order for its own line-item table. Group by region to compare totals, or select cells and export just that range.",
    panelScope: "Selection and export",
    panelScopeText:
      "Row selection powers bulk actions. Cell selection powers range export. They remain independent so each action has a clear scope.",
    assistantTitle: "Order desk assistant",
    assistantNote:
      "Scripted local assistant. No model, account, or external service is connected. Actions use the real table agent and its approval flow.",
    assistantGreeting:
      "I can select pending orders across this workspace or sort the order values.",
    suggestionReview: "Select pending orders",
    suggestionSort: "Highest value first",
    assistantUnknown:
      "Try “select pending orders” or “highest value first”. These are the two actions available in this local demonstration.",
    assistantUnavailable: "Resume the workspace to use the assistant.",
    assistantReviewDone:
      "Pending orders are selected across the workspace, including any hidden by filters. Open the Review queue to reveal one, or mark the selection ready.",
    assistantSortDone: "Orders are sorted by value, highest first.",
    assistantNotApplied:
      "The table did not apply this action. You can retry or keep working in the table.",
    assistantCapability: "Select orders awaiting review after your approval",
    dispatchTitle: "One plan, every moving part.",
    dispatchLead:
      "Expand a delivery run to see its orders. Reorder within a run using the move controls, then review the shared pickup windows below.",
    run: "Run / order",
    stops: "Stops",
    parcels: "Parcels",
    driver: "Driver",
    pickup: "Pickup window",
    vehicle: "Vehicle",
    destination: "Destination",
    dispatchNote:
      "Ready orders only. Review orders and completed shipments stay out of this plan. Selecting a run includes its loaded orders.",
    moved: "Dispatch order updated.",
    manifest: "Pickup manifest",
    manifestLead:
      "Consecutive deliveries share a pickup window on desktop. Cards repeat each field for clarity on small screens.",
    spanNote:
      "Merged cells describe adjacent deliveries. Search and export still use the individual delivery records.",
    revenueTitle: "See the pattern behind the orders.",
    revenueLead:
      "Compare regions, inspect the margin formula, and change the pivot without rebuilding the source data.",
    profit: "Gross profit",
    cost: "Cost",
    trend: "Recent order value",
    revenueTable: "Revenue by customer",
    pivot: "Regional summary",
    pivotLead:
      "Choose the row dimension and measure. The totals below come from the same twelve orders.",
    formulaNote:
      "Gross profit = order value − cost. Edit a cost to recalculate the formula. The six-point trend is fictional historical context.",
    scopeNote:
      "All amounts are in USD. This is a product demonstration, not financial reporting.",
  },
  ar: {
    manageViews: "إدارة طرق العرض المحفوظة",
    savedViewsHelp:
      "احفظ التصفية والترتيب والتجميع والكثافة من قائمة طرق العرض المحفوظة في الجدول. تبقى طرق العرض في هذا المتصفح عند توفر التخزين، ولا يغيّر تطبيقها تعديلات الطلبات الحالية. يفتح العرض الافتراضي مع رابط جديد، وتأخذ إعدادات الجدول الموجودة في الرابط الأولوية.",
    clearRange: "مسح تحديد الخلايا",
    rangeHelp:
      "حدّد خلايا في جدول سطح المكتب باستخدام Shift مع الأسهم ثم صدّرها. لن يُنشأ ملف دون نطاق محدّد حالي.",
    rangeMobile:
      "تصدير نطاق الخلايا غير متاح في البطاقات. اختر الصفحة أو كل الطلبات المصفّاة، أو عُد إلى جدول سطح المكتب وحدّد نطاقاً جديداً.",
    recoverySaved:
      "ستُستعاد الطلبات والتحديد وخطة الشحن المحلية بعد إعادة المحاولة. تبقى إعدادات الجدول والمحور في الرابط.",
    recoveryBlocked:
      "تعذّر حفظ عملك للاستعادة في هذا المتصفح. لم تتم إعادة التحميل. عُد إلى عرض آخر لمواصلة العمل.",
    queueHelp:
      "افتح طلباً معلّقاً لإظهاره وتحديده وفحص بنوده. تعمل القائمة على مساحة العمل كاملة، بما فيها الطلبات المخفية بعوامل التصفية الحالية.",
    queueEmpty: "لا توجد طلبات بانتظار المراجعة.",
    reviewing: "مراجعة",
    openDetails: "فتح بنود الطلب",
    van: "مركبة",
    deliveryRun: "مسار توصيل",
    ordersHint:
      "ابدأ بقائمة المراجعة أو ابحث باسم العميل. راجع البنود ثم ضع علامة جاهز على الطلبات المختارة لإضافتها إلى خطة الشحن.",
    dispatchHint:
      "تدخل الطلبات الجاهزة فقط إلى الخطة. تبقى طلبات المراجعة في المكتب وتُعدّ الطلبات المشحونة مكتملة. النقل وتغييرات المسؤول تتبع مساحة العمل المشتركة.",
    revenueHint:
      "عدّل التكلفة لمشاهدة إعادة حساب الربح الإجمالي. غيّر صفوف المحور أو المقياس لمقارنة الطلبات نفسها من زاوية أخرى.",
    ordersKeys:
      "استخدم Tab لعناصر التحكم. على سطح المكتب تنقّلك الأسهم وتحدّد Shift مع الأسهم خلايا. تستخدم البطاقات عناصر الصف. يغلق Escape النوافذ.",
    dispatchKeys:
      "على سطح المكتب ركّز مقبض النقل: Space للرفع والأسهم للنقل وSpace للوضع وEscape للإلغاء. في البطاقات استخدم النقل للأعلى أو الأسفل. يصل Tab لكل عنصر.",
    revenueKeys:
      "على سطح المكتب تنقّلك الأسهم ويعدّل F2 التكلفة. يصل Tab إلى خيارات المحور. توفّر البطاقات الحقل القابل للتحرير وأدوات الاختيار نفسها.",
    discovery: "ميزات هذا العرض",
    implementation: "كيف بُني هذا العرض",
    featureFinder: "ابحث عن ميزة أصلية",
    featureExamples: "أمثلة أصلية مركّزة",
    compare: "مقارنة حزمة متاحة",
    compareNote:
      "تُفتح المقارنات في علامة تبويب جديدة لتبقى مساحة عملك كما هي.",
    source: "مصدر المحوّل",
    sourceExample: "مثال من المصدر",
    viewReference: "مرجع الميزة",
    featureFilters: "التصفية والتحرير",
    featureNested: "الجداول المتداخلة",
    featureActions: "الإجراءات والتصدير",
    featureAssistant: "موافقات المساعد",
    featureViews: "طرق العرض المحفوظة",
    featureTree: "الصفوف الشجرية",
    featureMoves: "نقل الصفوف",
    featureSpans: "الخلايا المدمجة",
    featureNavigation: "التنقّل والبحث",
    featureGrouping: "التجميع",
    featureFormulas: "الصيغ والمحاور",
    featureColumns: "الأعمدة",
    featureFooters: "الملخّصات والتذييلات",
    featureSelection: "التحديد",
    featureComposition: "دورات حياة مركّبة",
    featureUnion: "ميزات نافذة البيانات",
    invalidCost: "أدخل تكلفة تساوي صفراً أو أكثر.",
    costSaved: "تم تحديث تكلفة",
    orderImplementation:
      "يمتلك المحوّل الأصلي عناصر التحكم وتملك دوال التطبيق التحرير والكتابة الجماعية. يعرض DataTable حقيقي آخر بنود الطلب. يتطلب تصدير النطاق تحديداً حالياً على سطح المكتب.",
    dispatchImplementation:
      "يعيّن التطبيق معرّفات الطلبات الجاهزة لمسارات المناطق. تطلب أدوات الشجرة والنقل الأصلية تغيير الخطة. يستخدم السجل دمج الصفوف بينما تكرّر البطاقات كل حقول التوصيل.",
    revenueImplementation:
      "يوفّر عمود الصيغة القيمة المحسوبة. يحدّث التحرير الأصلي تكلفة التطبيق وتحفظ حالة رابط المحور تغييرات الأبعاد والمقاييس بشكل مستقل عن جدول الطلبات.",
    brand: "AdaptTable",
    eyebrow: "Vue Unstyled / مساحة عمل تفاعلية",
    title: "طريقة أهدأ للعمل مع البيانات.",
    lead: "راجع الطلبات، وخطّط للشحن، وافهم الإيرادات. جداول حقيقية وتفاعلات مترابطة ومساحة مريحة للعمل.",
    notice: "بيانات خيالية وتغييرات محلية. حزم Vue تجريبية ولم تُنشر بعد.",
    orders: "مكتب الطلبات",
    dispatch: "خطة الشحن",
    revenue: "مراجعة الإيرادات",
    nav: "طرق عرض مساحة العمل",
    language: "اللغة",
    layout: "التخطيط",
    auto: "متجاوب",
    cards: "بطاقات",
    theme: "المظهر الداكن",
    guidance: "ابدأ من هنا",
    hint: "ابحث باسم العميل، وحدّد بعض الطلبات، وافتح تفاصيلها، أو اطلب من المساعد تجهيز المراجعة.",
    keyboard: "دليل لوحة المفاتيح",
    keyHint:
      "استخدم Tab للوصول إلى عناصر التحكم، والأسهم للتنقل في الجدول، وShift مع الأسهم لتحديد نطاق، وEscape لإغلاق النافذة.",
    docs: "دليل Vue",
    examples: "الأمثلة الأصلية",
    help: "حول مساحة العمل",
    about:
      "تستخدم مساحة العمل محوّل Vue Unstyled الحقيقي. عناصر التحكم HTML أصلية بتنسيق التطبيق، والتغييرات تبقى في جلسة المتصفح.",
    ready: "مساحة العمل جاهزة",
    footer: "مصمّم للعمل اليومي.",
    total: "الطلبات في مساحة العمل",
    needsReview: "بانتظار المراجعة",
    value: "قيمة الطلبات",
    selected: "محدّد",
    ordersTitle: "التفاصيل أمامك دائماً.",
    ordersLead:
      "ابحث عن الطلب التالي للمراجعة، وعدّل المسؤول، وافتح بنوده دون مغادرة موضعك.",
    group: "التجميع حسب المنطقة",
    groupingOff: "دون تجميع",
    groupingOn: "حسب المنطقة",
    exportScope: "التصدير",
    page: "الصفحة الحالية",
    loadedCards: "البطاقات المحمّلة",
    range: "الخلايا المحدّدة",
    all: "كل الطلبات المصفّاة",
    refresh: "استعادة البيانات التجريبية",
    refreshed: "تمت استعادة الطلبات التجريبية وخطة الشحن الأصلية.",
    pause: "إيقاف مساحة العمل مؤقتاً",
    resume: "استئناف مساحة العمل",
    paused: "مساحة العمل متوقفة مؤقتاً",
    pausedBody: "تم الاحتفاظ بطريقة العرض. استأنف العمل عندما تكون مستعداً.",
    local: "التغييرات محلية لهذا العرض التجريبي.",
    rowDetails: "بنود الطلب",
    customer: "العميل",
    order: "الطلب",
    owner: "المسؤول",
    status: "الحالة",
    due: "موعد الشحن",
    amount: "القيمة",
    region: "المنطقة",
    pageTotal: "إجمالي الصفحة",
    reviewNote:
      "تشمل الإجماليات الصفحة الحالية أو البطاقات المحمّلة على الهاتف. التصدير يستخدم النطاق المختار أعلاه.",
    product: "المنتج",
    quantity: "الكمية",
    unitPrice: "سعر الوحدة",
    subtotal: "الإجمالي الفرعي",
    noOrders: "لا توجد طلبات مطابقة",
    noOrdersHint: "جرّب اسم عميل آخر أو امسح عوامل التصفية.",
    clear: "مسح عوامل التصفية",
    loading: "جارٍ تحميل مساحة العمل…",
    failure: "تعذّر تحميل مساحة العمل",
    retry: "حاول مجدداً",
    saved: "تم تحديث المسؤول عن",
    invalidOwner: "أدخل حرفين على الأقل لاسم المسؤول.",
    bulk: "وضع علامة جاهز",
    bulkTitle: "تحديد الطلبات المختارة كجاهزة؟",
    bulkMessage:
      "ستصبح طلبات المراجعة المختارة جاهزة وتدخل خطة الشحن. تبقى الطلبات المكتملة مكتملة.",
    bulkDone: "طلبات أصبحت جاهزة.",
    command: "عرض الطلبات بانتظار المراجعة",
    commandDone: "طلبات بانتظار المراجعة معروضة ومحدّدة.",
    context: "تحديد هذا الطلب",
    contextDone: "تم تحديد",
    panel: "قائمة المراجعة",
    panelText:
      "يمكن تعديل المسؤول مباشرة. وسّع الطلب لعرض جدول بنوده. جمّع حسب المنطقة لمقارنة الإجماليات أو حدّد خلايا وصدّر نطاقها.",
    panelScope: "التحديد والتصدير",
    panelScopeText:
      "تحديد الصفوف يفعّل الإجراءات الجماعية، وتحديد الخلايا يحدّد نطاق التصدير. يعمل كل منهما بشكل مستقل.",
    assistantTitle: "مساعد مكتب الطلبات",
    assistantNote:
      "مساعد محلي مكتوب مسبقاً. لا يوجد نموذج أو حساب أو خدمة خارجية متصلة. الإجراءات تستخدم وكيل الجدول الحقيقي وخطوات الموافقة.",
    assistantGreeting:
      "أستطيع تحديد طلبات المراجعة في مساحة العمل أو ترتيب قيم الطلبات.",
    suggestionReview: "تحديد طلبات المراجعة",
    suggestionSort: "الأعلى قيمة أولاً",
    assistantUnknown:
      "جرّب «تحديد طلبات المراجعة» أو «الأعلى قيمة أولاً». هذان هما الإجراءان المتاحان في هذا العرض المحلي.",
    assistantUnavailable: "استأنف مساحة العمل لاستخدام المساعد.",
    assistantReviewDone:
      "تم تحديد الطلبات المعلّقة في مساحة العمل، بما فيها المخفية بالتصفية. افتح قائمة المراجعة لإظهار طلب أو ضع علامة جاهز على التحديد.",
    assistantSortDone: "تم ترتيب الطلبات حسب القيمة من الأعلى إلى الأقل.",
    assistantNotApplied:
      "لم يطبّق الجدول هذا الإجراء. يمكنك المحاولة مجدداً أو مواصلة العمل.",
    assistantCapability: "تحديد الطلبات بانتظار المراجعة بعد موافقتك",
    dispatchTitle: "خطة واحدة لكل التفاصيل.",
    dispatchLead:
      "وسّع مسار التوصيل لعرض طلباته. أعد ترتيب الطلبات داخل المسار، ثم راجع أوقات الاستلام المشتركة أدناه.",
    run: "المسار / الطلب",
    stops: "المحطات",
    parcels: "الطرود",
    driver: "السائق",
    pickup: "وقت الاستلام",
    vehicle: "المركبة",
    destination: "الوجهة",
    dispatchNote:
      "الطلبات الجاهزة فقط. تبقى طلبات المراجعة والشحنات المكتملة خارج الخطة. تحديد المسار يشمل طلباته المحمّلة.",
    moved: "تم تحديث ترتيب الشحن.",
    manifest: "سجل الاستلام",
    manifestLead:
      "التوصيلات المتتالية تشترك في وقت استلام على سطح المكتب. البطاقات تكرّر الحقول لتوضيحها على الشاشات الصغيرة.",
    spanNote:
      "الخلايا المدمجة تصف التوصيلات المتجاورة. البحث والتصدير يستخدمان السجلات الفردية.",
    revenueTitle: "اكتشف النمط وراء الطلبات.",
    revenueLead:
      "قارن المناطق، وافحص صيغة الهامش، وغيّر الجدول المحوري دون إعادة إنشاء البيانات.",
    profit: "الربح الإجمالي",
    cost: "التكلفة",
    trend: "قيمة الطلبات الأخيرة",
    revenueTable: "الإيرادات حسب العميل",
    pivot: "ملخّص المناطق",
    pivotLead:
      "اختر بُعد الصف والمقياس. الإجماليات أدناه تأتي من الطلبات الاثني عشر نفسها.",
    formulaNote:
      "الربح الإجمالي = قيمة الطلب − التكلفة. عدّل التكلفة لإعادة حساب الصيغة. الاتجاه من ست نقاط سياق تاريخي خيالي.",
    scopeNote:
      "جميع المبالغ بالدولار الأمريكي. هذا عرض للمنتج وليس تقريراً مالياً.",
  },
} as const;
