/**
 * `@adapttable/<kit>/features` — the feature factories and every type they
 * hand back, forwarded from `@adapttable/core/features`.
 *
 * The explicit manifest keeps shadcn's second-level forwarding surface exact;
 * a nested wildcard can expose core's private bundle symbols.
 *
 * @packageDocumentation
 */
export {
  type Aggregator,
  applyTableFeatures,
  batchEditing,
  type BatchRowEdit,
  type BulkAction,
  bulkActions,
  cellNavigation,
  cellSpan,
  type CellSpanAppearance,
  collapsibleColumnGroups,
  columnMenu,
  type ColumnMenuAction,
  type ColumnMenuActionContext,
  type ColumnMenuRow,
  columnSelectionCheckbox,
  type Command,
  commandPalette,
  type CommandPaletteOptions,
  contextMenu,
  type ContextMenuItem,
  type ContextMenuOptions,
  type ContextMenuTarget,
  type CustomCellEditorRender,
  densityChooser,
  dirtyIndicators,
  editHistory,
  editing,
  exportCsv,
  type ExportCsvOptions,
  type ExportWriter,
  type ExtraRow,
  extraRows,
  feature,
  type FeatureApplyInput,
  type FeaturePatch,
  type FilterDef,
  filters,
  filterTypes,
  type FilterTypeSpec,
  findInTable,
  fitColumns,
  fullscreen,
  type GetCellSpan,
  grouping,
  type GroupSort,
  headerFilters,
  multiSort,
  nestedTable,
  type NestedTableFor,
  print,
  resizableColumns,
  rowActions,
  rowAppearance,
  rowDetail,
  rowEditing,
  type RowHeight,
  rowPinning,
  type RowPinState,
  rowReorder,
  type RowReorderHandler,
  type RowStyle,
  savedViews,
  selectionStats,
  sidePanel,
  type SidePanelEntry,
  type SidePanelOptions,
  statusBar,
  type TableFeature,
  type TableFeatureHost,
  tree,
  undoRedoButtons,
  type UseSavedViewsOptions,
  useTableFeatures,
  virtualize,
} from "@adapttable/core/features";
