/** Queries kit-owned DOM without expanding the public part contract. */
const KIT_SELECTORS: Readonly<Record<string, string>> = {
  "assistant-examples-list": '[data-clarity-part="assistant-examples-list"]',
  checkbox: '[data-clarity-part="checkbox"]',
  "column-menu": '[data-clarity-part="column-menu"]',
  "column-menu-auto-size": '[data-clarity-part="column-menu-auto-size"]',
  "column-menu-choice-label": '[data-clarity-part="column-menu-choice-label"]',
  "column-menu-choice-select":
    '[data-clarity-part="column-menu-choice-select"]',
  "column-menu-grip": '[data-clarity-part="column-menu-grip"]',
  "column-menu-header": '[data-clarity-part="column-menu-header"]',
  "column-menu-label": '[data-clarity-part="column-menu-label"]',
  "column-menu-panel": '[data-clarity-part="column-menu-panel"]',
  "column-menu-pin": '[data-clarity-part="column-menu-pin"]',
  "column-menu-reset": '[data-clarity-part="column-menu-reset"]',
  "column-menu-separator": '[data-clarity-part="column-menu-separator"]',
  "column-menu-title": '[data-clarity-part="column-menu-title"]',
  "column-menu-visibility": '[data-clarity-part="column-menu-visibility"]',
  "empty-clear": '[data-clarity-part="empty-clear"]',
  "expand-button": '[data-clarity-part="expand-button"]',
  "export-spinner": '[data-clarity-part="export-spinner"]',
  "filter-checkbox-group": '[data-clarity-part="filter-checkbox-group"]',
  "filter-options-loading": '[data-clarity-part="filter-options-loading"]',
  "filters-anchor": '[data-clarity-part="filters-anchor"]',
  "filters-body": '[data-clarity-part="filters-body"]',
  "filters-button": '[data-clarity-part="filters-button"]',
  "filters-clear": '[data-clarity-part="filters-clear"]',
  "filters-count": '[data-clarity-part="filters-count"]',
  "filters-done": '[data-clarity-part="filters-done"]',
  "filters-footer": '[data-clarity-part="filters-footer"]',
  "filters-header": '[data-clarity-part="filters-header"]',
  "filters-icon": '[data-clarity-part="filters-icon"]',
  "filters-popover": '[data-clarity-part="filters-popover"]',
  "filters-title": '[data-clarity-part="filters-title"]',
  "load-more": '[data-clarity-part="load-more"]',
  "load-more-button": '[data-clarity-part="load-more-button"]',
  loading: '[data-clarity-part="loading"]',
  "loading-card": '[data-clarity-part="loading-card"]',
  "loading-cards": '[data-clarity-part="loading-cards"]',
  "loading-cell": '[data-clarity-part="loading-cell"]',
  "loading-header-cell": '[data-clarity-part="loading-header-cell"]',
  "loading-header-row": '[data-clarity-part="loading-header-row"]',
  "loading-line": '[data-clarity-part="loading-line"]',
  "loading-row": '[data-clarity-part="loading-row"]',
  "loading-table": '[data-clarity-part="loading-table"]',
  "page-ellipsis": '[data-clarity-part="page-ellipsis"]',
  "page-next": '[data-clarity-part="page-next"]',
  "page-number": '[data-clarity-part="page-number"]',
  "page-prev": '[data-clarity-part="page-prev"]',
  pager: '[data-clarity-part="pager"]',
  "refresh-indicator": '[data-clarity-part="refresh-indicator"]',
  "retry-button": '[data-clarity-part="retry-button"]',
  "rows-per-page": '[data-clarity-part="rows-per-page"]',
  "sort-button": '[data-clarity-part="sort-button"]',
  "sort-index": '[data-clarity-part="sort-index"]',
  "sort-select": '[data-clarity-part="sort-select"]',
  "views-button": '[data-clarity-part="views-button"]',
  "views-delete": '[data-clarity-part="views-delete"]',
  "views-divider": '[data-clarity-part="views-divider"]',
  "views-input": '[data-clarity-part="views-input"]',
  "views-item": '[data-clarity-part="views-item"]',
  "views-menu": '[data-clarity-part="views-menu"]',
  "views-panel": '[data-clarity-part="views-panel"]',
  "views-row": '[data-clarity-part="views-row"]',
  "views-save": '[data-clarity-part="views-save"]',
  "views-save-row": '[data-clarity-part="views-save-row"]',
  "virtual-spacer": '[data-clarity-part="virtual-spacer"]',
  "filters-panel": "clr-side-panel .modal-dialog",
  "filters-backdrop": "clr-side-panel .modal-backdrop",
  "filters-close": "clr-side-panel .close",
};

export const kitPart = (name: string): string =>
  KIT_SELECTORS[name] ?? `[data-adapttable-part="${name}"]`;
