import type {
  AggregateSpec,
  CellEditor,
  ColumnInput,
  ComponentRenderer,
  FeatureMountContext,
  FeatureState,
  FeatureStateKey,
  FilterRuntime,
  HeaderFilterModel,
  ResolvedTableOptions,
  RowActionControlsProjector,
  StaticFeatureHost,
  TableFeatureHost,
  TableRuntimeView,
  TableSummaryCellModel,
  TableSummaryModel,
  UseDataTableShellOptions,
  UseDataTableShellResult,
  VueHeaderFilterControlProps,
} from "@adapttable/vue";
interface Row {
  id: string;
  value: number;
}
export type NamedMembers = [
  AggregateSpec,
  CellEditor,
  ColumnInput<Row>,
  ComponentRenderer<{ value: number }>,
  FeatureMountContext<Row>,
  FeatureState,
  FeatureStateKey<number>,
  FilterRuntime<Row>,
  HeaderFilterModel<Row>,
  ResolvedTableOptions<Row>,
  RowActionControlsProjector<Row>,
  StaticFeatureHost,
  TableFeatureHost<Row>,
  TableRuntimeView<Row>,
  TableSummaryCellModel<Row>,
  TableSummaryModel<Row>,
  UseDataTableShellOptions<Row>,
  UseDataTableShellResult<Row>,
  VueHeaderFilterControlProps<Row>,
];
