import type {
  CellContext,
  DirtyEdits as AdapterDirtyEdits,
  DirtyEdits as BatchDirtyEdits,
  DirtyEdits,
  DirtyEdits as FeatureDirtyEdits,
  FeatureMountContext as BatchMountContext,
  FeatureMountContext as DensityMountContext,
  FeatureMountContext as EditingMountContext,
  FeatureMountContext as FilterMountContext,
  FeatureMountContext as FullscreenMountContext,
  FeatureMountContext as HeaderMountContext,
  FeatureMountContext as SavedViewsMountContext,
  FooterContext,
  HeaderContext,
  Renderer,
  StaticFeatureHost as DensityStaticHost,
  StaticFeatureHost as EditingStaticHost,
  StaticFeatureHost as FilterStaticHost,
  StaticFeatureHost as FullscreenStaticHost,
  StaticFeatureHost as HeaderStaticHost,
  StaticFeatureHost as SavedViewsStaticHost,
  TableFeatureHost as BatchHost,
  TableFeatureHost as EditingHost,
  TableFeatureHost as FilterHost,
  useGroupCollapseUrlState,
  UseGroupCollapseUrlStateOptions,
  UseGroupCollapseUrlStateResult,
  useRowPinningUrlState,
  UseRowPinningUrlStateOptions,
  UseRowPinningUrlStateResult,
  UseSavedViewsResult as DensityViews,
  UseSavedViewsResult as FullscreenViews,
} from "@adapttable/vue";
interface Row {
  readonly id: string;
}
export type SubpathMembers = [
  typeof useGroupCollapseUrlState,
  UseGroupCollapseUrlStateOptions,
  UseGroupCollapseUrlStateResult,
  typeof useRowPinningUrlState,
  UseRowPinningUrlStateOptions,
  UseRowPinningUrlStateResult,
  DirtyEdits,
  AdapterDirtyEdits,
  FeatureDirtyEdits,
  FilterMountContext<Row>,
  FilterStaticHost,
  FilterHost<Row>,
  HeaderMountContext<Row>,
  HeaderStaticHost,
  CellContext<Row>,
  EditingMountContext<Row>,
  FooterContext<Row>,
  HeaderContext<Row>,
  Renderer<CellContext<Row>>,
  EditingStaticHost,
  EditingHost<Row>,
  BatchDirtyEdits,
  BatchMountContext<Row>,
  BatchHost<Row>,
  DensityMountContext<Row>,
  DensityStaticHost,
  DensityViews,
  FullscreenMountContext<Row>,
  FullscreenStaticHost,
  FullscreenViews,
  SavedViewsMountContext<Row>,
  SavedViewsStaticHost,
];
