/**
 * `@adapttable/<kit>/features` — the feature factories and every type they
 * hand back, forwarded from `@adapttable/core/features`.
 *
 * The whole surface, not the factories alone: a host writing its own
 * `TableFeature` names `Aggregator`, `ExportWriter`, `FilterTypeSpec`,
 * `SidePanelEntry`, `Command` and `CustomCellEditorRender` to register
 * anything on the host, and reaching into `@adapttable/core` for them is the
 * one thing importing from your kit is meant to avoid.
 *
 * Every kit forwards the same list, so `etc/api-contract.json` gives all of
 * them one shared `kit/features` surface: a kit that stops forwarding a name
 * fails the contract check against the other seven.
 */
export {
  type Aggregator,
  applyTableFeatures,
  batchEditing,
  type BatchRowEdit,
  type BulkAction,
  bulkActions,
  cellNavigation,
  cellSpan,
  type CellSpanAppearance,
  collapsibleColumnGroups,
  columnMenu,
  type ColumnMenuAction,
  type ColumnMenuActionContext,
  type ColumnMenuRow,
  columnSelectionCheckbox,
  type Command,
  commandPalette,
  type CommandPaletteOptions,
  contextMenu,
  type ContextMenuItem,
  type ContextMenuOptions,
  type ContextMenuTarget,
  type CustomCellEditorRender,
  densityChooser,
  dirtyIndicators,
  editHistory,
  editing,
  exportCsv,
  type ExportCsvOptions,
  type ExportWriter,
  type ExtraRow,
  extraRows,
  feature,
  type FeatureApplyInput,
  type FeaturePatch,
  type FilterDef,
  filters,
  filterTypes,
  type FilterTypeSpec,
  findInTable,
  fitColumns,
  fullscreen,
  type GetCellSpan,
  grouping,
  type GroupSort,
  headerFilters,
  multiSort,
  nestedTable,
  type NestedTableFor,
  resizableColumns,
  rowAppearance,
  rowDetail,
  rowEditing,
  type RowHeight,
  rowPinning,
  type RowPinState,
  rowReorder,
  type RowReorderHandler,
  type RowStyle,
  savedViews,
  selectionStats,
  sidePanel,
  type SidePanelEntry,
  type SidePanelOptions,
  statusBar,
  type TableFeature,
  type TableFeatureHost,
  tree,
  undoRedoButtons,
  type UseSavedViewsOptions,
  useTableFeatures,
  virtualize,
} from "@adapttable/core/features";
