/** Angular-only kit setup guides; these have no React documentation counterpart. */
export const ANGULAR_KIT_DOCS = Object.freeze([
  "material",
  "ng-bootstrap",
  "spartan",
  "taiga-ui",
  "angular-cdk",
  "ngx-bootstrap",
  "aria",
]);

/** Canonical Angular guide sources, in reading order. Safe to import in apps. */
export const ANGULAR_DOCS = Object.freeze(
  [
    "getting-started",
    "migrating-to-0-5",
    ...ANGULAR_KIT_DOCS,
    "features",
    "data-tiers",
    "headless",
    "custom-table-source",
    "building-an-adapter",
    "columns",
    "column-groups",
    "sparkline",
    "sorting",
    "search",
    "filtering",
    "filter-tree",
    "header-filters",
    "custom-filter-types",
    "pagination",
    "selection",
    "row-actions",
    "row-expansion",
    "nested-tables",
    "cell-editing",
    "row-reordering",
    "row-pinning",
    "pinned-summary-rows",
    "row-spanning",
    "full-width-rows",
    "row-styling",
    "cell-navigation",
    "row-grouping",
    "aggregation",
    "pivot",
    "formulas",
    "tree-data",
    "column-management",
    "saved-views",
    "virtualization",
    "mobile",
    "url-state",
    "exporting",
    "export-xlsx",
    "export-pdf",
    "ssr-rsc",
    "agent-capabilities",
    "ai-voice",
    "customization",
    "toolbar-and-view-controls",
    "command-palette",
    "i18n-rtl",
    "accessibility",
    "realtime",
  ].map((page) => `angular/${page}.md`)
);
