/** Material internals are tested through the kit's native widget classes; public parts stay exact. */
const MATERIAL_INTERNALS = new Set([
  "assistant-examples-list",
  "filters-anchor",
  "filters-backdrop",
  "filters-body",
  "filters-button",
  "filters-clear",
  "filters-close",
  "filters-count",
  "filters-done",
  "filters-footer",
  "filters-header",
  "filters-icon",
  "filters-panel",
  "filters-popover",
  "filters-title",
  "filter-checkbox-group",
  "filter-options-loading",
  "column-menu",
  "column-menu-auto-size",
  "column-menu-choice-label",
  "column-menu-choice-select",
  "column-menu-grip",
  "column-menu-header",
  "column-menu-label",
  "column-menu-panel",
  "column-menu-pin",
  "column-menu-reset",
  "column-menu-separator",
  "column-menu-title",
  "column-menu-visibility",
  "views-button",
  "views-delete",
  "views-divider",
  "views-input",
  "views-item",
  "views-menu",
  "views-panel",
  "views-row",
  "views-save",
  "views-save-row",
  "page-ellipsis",
  "page-next",
  "page-number",
  "page-prev",
  "pager",
  "rows-per-page",
  "load-more",
  "load-more-button",
  "loading",
  "loading-card",
  "loading-cards",
  "loading-cell",
  "loading-header-cell",
  "loading-header-row",
  "loading-line",
  "loading-row",
  "loading-table",
  "refresh-indicator",
  "checkbox",
  "empty-clear",
  "expand-button",
  "export-spinner",
  "retry-button",
  "sort-button",
  "sort-index",
  "sort-select",
  "virtual-spacer",
]);

export function kitSelector(name: string): string {
  return MATERIAL_INTERNALS.has(name)
    ? `.adapt-material-${name}`
    : `[data-adapttable-part="${name}"]`;
}
