import { defineConfig } from "tsdown";
import Vue from "unplugin-vue/rolldown";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/filters.ts",
    "src/grouping.ts",
    "src/density.ts",
    "src/fullscreen.ts",
    "src/header-filters.ts",
    "src/row-actions.ts",
    "src/row-detail.ts",
    "src/tree.ts",
    "src/editing.ts",
    "src/batch-editing.ts",
    "src/cell-navigation.ts",
    "src/column-selection.ts",
    "src/status-bar.ts",
    "src/selection-stats.ts",
    "src/find-in-table.ts",
    "src/sparkline.ts",
    "src/stream.ts",
    "src/cell-span.ts",
    "src/column-groups.ts",
    "src/extra-rows.ts",
    "src/fit-columns.ts",
    "src/formula.ts",
    "src/multi-sort.ts",
    "src/pinned-summary-rows.ts",
    "src/resizable-columns.ts",
    "src/row-appearance.ts",
    "src/row-pinning.ts",
    "src/virtualize.ts",
    "src/columns.ts",
    "src/rows.ts",
    "src/nested-table.ts",
    "src/bulk-actions.ts",
    "src/print.ts",
    "src/export.ts",
    "src/export-csv.ts",
    "src/export-pdf.ts",
    "src/export-xlsx.ts",
    "src/column-menu.ts",
    "src/saved-views.ts",
    "src/context-menu.ts",
    "src/command-palette.ts",
    "src/side-panel.ts",
    "src/grouping-panel.ts",
    "src/row-reorder.ts",
    "src/pivot.ts",
    "src/assistant.ts",
    "src/features.ts",
    "src/preset.ts",
  ],
  platform: "neutral",
  format: ["esm", "cjs"],
  tsconfig: "./tsconfig.build.json",
  plugins: [Vue({ isProduction: true })],
  css: { fileName: "styles.css", splitting: false, inject: false },
  dts: { vue: true },
  sourcemap: true,
  clean: true,
  treeshake: true,
  deps: { neverBundle: ["vue", "reka-ui", /^@adapttable\/vue(?:\/.*)?$/] },
  outExtensions: ({ format }) => ({
    js: format === "es" ? ".js" : ".cjs",
    dts: format === "es" ? ".d.ts" : ".d.cts",
  }),
});
